cloud-gov/site

- styles/_mermaid.scss
- styles/_theme.scss
- styles/overrides/_hero.scss
- styles/pages/_index.scss
- styles/styles.scss
- styles/theme/_uswds-theme-custom-styles.scss
- Migrating styles from jekyll
> Chore styles migration

- js/app.js
- Migrating javascript from jekyll site
> Chore javascript migration

- content/knowledge-base/articles/2021-05-17-troubleshooting-ssh-connections.md
- content/knowledge-base/articles/2021-05-20-connecting-to-brokered-service-instances.md
- content/knowledge-base/articles/2021-05-20-getting-rds-version-information.md
- content/knowledge-base/articles/2021-05-20-managing-buildpack-changes.md
- content/knowledge-base/articles/2021-05-24-secureauth-issues.md
- content/knowledge-base/articles/2021-07-26-app-restarts.md
- content/knowledge-base/articles/2021-09-15-creating-external-domain-service.md
- content/knowledge-base/articles/2021-09-21-sending-emails-from-clouddotgov.md
- content/knowledge-base/articles/2021-10-05-restricting-access-to-apps.md
- content/knowledge-base/articles/2021-12-16-managing-egress-traffic.md
- content/knowledge-base/articles/2022-05-05-creating-postgresql-databases-from-shared-rds.md
- content/knowledge-base/articles/2022-08-08-adding-users-to-sandbox.md
- content/knowledge-base/articles/2022-11-04-Encryption-In-Transit.md
- content/knowledge-base/articles/2022-11-04-fixing-certificate-errors-aws-egress-proxy.md
- content/knowledge-base/articles/2022-12-08-common-kibana-searches-on-clouddotgov.md
- content/knowledge-base/articles/2023-02-13-Connecting-PostgreSQL-RDS-instance-to-S3.md
- content/knowledge-base/articles/2023-03-28-CloudFoundry-Key-Error.md
- content/knowledge-base/articles/2023-04-18-Sidecar-Processes.md
- content/knowledge-base/articles/2023-08-07-advantages-of-multiple-application-instances.md
- content/knowledge-base/articles/2024-03-25-monitoring-app-metrics.md
- content/knowledge-base/articles/2024-24-01-how-cloud.gov-continually-adapts-to-dynamic-cybersecurity-threats.md
- content/knowledge-base/articles/articles.11tydata.js
- content/knowledge-base/index.html
> added knowledge base from cg-site and configured permalinks

- _includes/layouts/base.html
- _includes/pages/components/alert--best-practice.html
- _includes/pages/components/alert--note.html
- _includes/pages/components/alert--tip.html
- _includes/pages/components/alert.html
- _includes/pages/components/glossary.html
- _includes/pages/logo.html
- _includes/pages/sidenav.html
- content/pages/index.liquid
- content/pages/pages.11tydata.js
Initial commit for pages. Includes header and general layout and menu.
> init pages

- content/pages/documentation/previews.md
- content/pages/documentation/search.md
- add documentation to the pages section pertaining to site indexing and crawling
N/A
> Chore: additional pages documentation

- content/pages/documentation/node-on-pages.md
- minor documentation edits, add backticks 
N/A
> chore: Minor updates to documentation

- content/pages/features.liquid
> chore: Update language

- content/docs/services/relational-database.md
- content/knowledge-base/articles/2021-05-24-secureauth-issues.md
- content/news/articles/2025-01-02-v2api-deprecation.md
- Added update guidance and links to the v3 upgrade guide and the v2 docs.
- Add PITR - point-in-time recovery
- Make support request easier to find, and more complete
- reference: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PIT.html
N/A
> chore: V2 to V3 + add PITR documentation

- _includes/footer.html
- Brings content in line with current production footer
None
> Update footer text to match live site

- content/pages/pricing.liquid
- added margin to feature list
none, visual content only
> fixed text alignment issues on Pages Pricing page

- content/knowledge-base/articles/2021-05-20-getting-rds-version-information.md
- content/knowledge-base/articles/2021-12-16-managing-egress-traffic.md
- content/knowledge-base/articles/2022-05-05-creating-postgresql-databases-from-shared-rds.md
- content/knowledge-base/articles/2024-12-06-migrating-opensearch.md
- content/pages/documentation/cloud-gov.md
- content/pages/index.liquid
Fixed broken links in Pages index and documentation pages
Fixed broken links in Knowledge Base articles
None, fixing broken links
> fixing broken links in Pages and Knowledge Base

- content/pages/documentation/custom-domains.md
- Convert 2 markdown tables in pages documentation to html to take advantage of the uswds table scrollability component
N/A
> convert markdown to html/add scrollability uswds component

- README.md
- Update `README.md` from template language to `cg-site` language
N/A
> WIP update README.md

- content/docs/services/app-autoscaler.md
- content/docs/services/aws-elasticache.md
- content/docs/services/aws-elasticsearch.md
- content/docs/services/cdn-route.md
- content/docs/services/cloud-gov-identity-provider.md
- content/docs/services/cloud-gov-service-account.md
- content/docs/services/custom-domains.md
- content/docs/services/external-domain-service.md
- content/docs/services/relational-database.md
- content/docs/services/s3.md
- Add proper frontmatter to services to display in docs sidenav
Fixes https://github.com/cloud-gov/site/issues/94
None
> Show services in side nav

- content/docs/customer-stories/fec.md
- fix customer story formatting
- Resolves #95 
N/A
> fix formatting

- content/index.md
- styles/_theme.scss
- Remove pricing packages from homepage as per https://gsa-tts.slack.com/archives/C06PM66GSAU/p1744162960395509?thread_ts=1744133480.058269&cid=C06PM66GSAU
None
> Remove pricing packages from homepage

- _includes/meta.html
- Adds `noindex,nofollow` robots to non production previews
None
> Make robots meta tag conditional

- _includes/meta.html
> Remove robots meta tag

- content/docs/getting-started/.SIDENAVCATEGORY
- content/knowledge-base/articles/2024-12-09-apt-buildpack-cache-issue.md
- content/knowledge-base/articles/2025-03-27-monitoring-app-metrics-opensearch.md
- Add missing KB article
- Update language
- Update image references
- Update "Getting Started" uswds icon
N/A
> add kb article/update langauge + icon

- README.md
- content/docs/services/external-domain-service.md
Closes #116 
None, this documentation is public and non-sensitive
> Fix external domain service docs rendering

- content/docs/compliance/pentest.md
-
- Address support requests like "AWS WAF Challanges during Scanning" with a specific policy language
-
Requires compliance OK.
> We won't adjust security for your scan

- content/sitemap.njk
- Use absolute url in sitemap items
None
> Use absolute url in sitemap

- content/docs/management/one-off-tasks.md
-
- The second example here is pending https://github.com/cloud-gov/cf-hello-worlds/pull/173
- I feel like this section could be better, but providing examples is a step in the right direction
Safe. References example code
> Add cron examples

- .eleventy.js
- _data/collections.yaml
- package-lock.json
- package.json
> Update 11ty to v3

- .eleventy.js
- package-lock.json
- package.json
- Uses virtual templates, available in latest version of RSS plugin
- Fixes https://github.com/cloud-gov/site/issues/119
- Preview: https://federalist-f689d682-d20c-4d0b-af7b-c1a42fcd49f5.sites.pages.cloud.gov/preview/cloud-gov/site/bh-new-rss/updates.xml
None
> Add RSS feed for news

- content/pages/knowledge-base/articles/website-api.md
- update imported modules
- update code snippets
- update some terminology to reflect changes in application
N/A
> Update article to reflect app changes

- content/news/articles/2025-06-09-metrics-opensearch.md
- remove colon from article title to fix build issue
None
> remove colon from article title

- _includes/pagination-links.html
fixed some errors in `pagination-links.html` that were causing duplicate pages to appear in the pagination 
none
> fixed pagination issues for knowledge base page

- content/docs/orgs-spaces/limits.md
- content/docs/orgs-spaces/new-org.md
- content/docs/orgs-spaces/roles.md
- content/docs/orgs-spaces/sso.md
- Added `showInSidenav: true` to the front matter of the following files >> `limits.md` `new-org.md` `roles.md` `sso.md`
N/A
Closes #150
> fix: Add YAML front matter to show in sidebar nav

- src/data/pages/workshop.yaml
- Adding placeholder hero copy for review
- Adding placeholder subhed copy for review
[None, just copy -- and getting situated in the site flow]
> Adding Workshop copy to Cloud.gov site

- src/data/pages/support.yaml
- fix broken link to knowledge base articles
None, just fixing a broken link
> fix broken link to knowledge base

- src/data/pages/home.yaml
- src/data/pages/security.yaml
- This PR clarifies that the listed compliance activities apply to the Cloud.gov platform layer, not to customer applications. The update ensures accuracy and prevents conflation of platform-managed security with customer responsibilities.
This improves content accuracy while also ensuring YAML validity.
> Improvements to security language to increase accuracy
